// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/gmCallback.tsx";
import * as $2 from "./routes/api/roll.tsx";
import * as $3 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/gmCallback.tsx": $1,
    "./routes/api/roll.tsx": $2,
    "./routes/index.tsx": $3,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
